
services:
  remote_auth:
    container_name: remote_auth
    build: ./open_auth
    volumes:
      - oauth_volume:/django
    ports:
      - "8080:8000" #host port changed to 8080
    networks:
      - nw
    depends_on:
      - postgreDB
    restart: on-failure  # Ensures container restarts if it fails
    env_file:
      - .env  # Add this line
    
  postgreDB:
    image: postgres:16
    container_name: postgreDB
    volumes:
      - /home/oryadi/ayoub/data/db:/var/lib/postgresql/data  
    ports:
      - 5434:5432
    networks:
      - nw
  nginx:
    build: ./nginx  # Ensure this points to your Nginx directory with the Dockerfile and nginx.conf
    ports:
      - "8082:443"
    depends_on:
      - remote_auth
    volumes:
      - front_volume:/var/www/front  # Front-end files volume
    networks:
      - nw
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6380:6379
    networks:
      - nw
  xo_game:
    container_name: XO
    build: ./Xo_Game/xo_game/
    ports:
      - 8001:8001
    depends_on:
      - postgreDB
    networks:
      - nw
    env_file:
      - .env 
  chatapp:
    container_name: chatapp
    build: ./chatapp
    ports:
      - 8003:8003
    depends_on:
      - chat_db
    env_file:
      - .env
    networks:
      - nw
    
  chat_db:
    image: postgres:latest
    container_name: chat_db
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    restart: on-failure:5
    volumes:
      - /home/oryadi/ayoub/data/chat_db:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - nw
  pingpong:
    container_name: pong
    build: ./PingPong/pinpong/pinpong/
    volumes:
      - pongs_volume:/PINPONG
    ports:
      - 8002:8002
    depends_on:
      - postgreDB
    networks:
      - nw
    env_file:
      - .env 
volumes:
  database-postgres:
  postgre_volume:
  front_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./nginx/srcs
  oauth_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./open_auth
  pongs_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./PingPong/pinpong/pinpong/
networks:
  nw:
    driver: bridge