# Generated by Django 4.2.10 on 2024-12-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('players', models.IntegerField(default=0)),
                ('is_reserved', models.IntegerField(default=0)),
            ],
        ),
    ]
