# Generated by Django 4.2.10 on 2024-11-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0012_user_info_loss_user_info_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='draw',
            field=models.IntegerField(default=0),
        ),
    ]
