# Generated by Django 4.2.10 on 2024-11-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0014_alter_user_info_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='draw',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='loss',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='win',
            field=models.IntegerField(),
        ),
    ]
