# Generated by Django 4.2.10 on 2024-11-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0017_alter_user_info_draw_alter_user_info_loss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
