# Generated by Django 4.2.10 on 2024-12-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0020_alter_user_info_draw_alter_user_info_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='intra_user',
            field=models.BooleanField(default=False),
        ),
    ]
