# Generated by Django 4.2.10 on 2024-08-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermangement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfriend',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
