# Generated by Django 4.2.10 on 2024-12-12 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermangement', '0007_matchhistoric_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistoric',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
